<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8">
		<?php //echo $this->headTitle() . "\n"?>
		<title>ITMG</title>
		<!-- Start : CSS -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/ext-all.css')?>" type="text/css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/dashboard.css')?>" type="text/css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('resources/css/icons.css')?>" type="text/css" />
		<!-- End of : CSS -->
		<!-- Start : JS -->
		<script type="text/javascript" src="<?php echo $this->baseUrl('resources/js/ext-all.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('resources/js/jquery.min.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('resources/js/base64.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('resources/js/func.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('apps/js/models')?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('apps/js/stores')?>"></script>
		<script type="text/javascript">
			Ext.define('sd', {
				singleton: true,
				baseUrl: '<?php echo $this->baseUrl()?>',
				nav: {
					width: 130,
					height: 26
				},
				content: {
					height: 200
				},
				groups: <?php echo Zend_Json::encode($this->groups) . "\n"?>
			});
			function makeid(length){
			    var text = "";
			    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

			    for( var i=0; i < length; i++ )
			        text += possible.charAt(Math.floor(Math.random() * possible.length));

			    return text;
			}
			Ext.onReady(function(){
				loadMenus();
				Ext.create('Ext.tab.Panel', {
					renderTo: 'content',
					id: 'main-content',
					padding: '1 0 0 0',
					height: Ext.getBody().getViewSize().height - $('.head').height() - $("#nav").height() - 30
				});
				
				Ext.EventManager.onWindowResize(function() {
					var content = Ext.getCmp('main-content');
					content.height = Ext.getBody().getViewSize().height - $('.head').height() - $("#nav").height();
					content.doLayout();
				});
			});
		</script>
		<!-- End of : JS -->
	</head>
	<body>
		<div class="logout-box">
			<p>Welcome, <?php echo $this->active_user ?> | <a href="<?php echo $this->url(array('module'=>'dashboard','controller'=>'login','action'=>'logout'),null,true)?>"><img src="<?php echo $this->baseUrl('images/logout.png')?>"/> Logout</a></p>
		</div>
		<div class="head">
			<img class="logo" src="<?php echo $this->baseUrl('images/logo.png')?>" />
		</div>
		<div id="nav"></div>
		<div id="content">
			<?php echo $this->layout()->content . "\n"?>
		</div>
	</body>
</html>